import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'Button/index': 'src/Button/index.ts',
    'Tooltip/index': 'src/Tooltip/index.ts',
    'Toast/index': 'src/Toast/index.ts',
    'Skeleton/index': 'src/Skeleton/index.ts',
    'ProgressBar/index': 'src/ProgressBar/index.ts',
    'Breadcrumb/index': 'src/Breadcrumb/index.ts',
    'Tabs/index': 'src/Tabs/index.ts',
    'Accordion/index': 'src/Accordion/index.ts',
    'ThemeToggle/index': 'src/ThemeToggle/index.ts',
    'Modal/index': 'src/Modal/index.ts',
    'Dropdown/index': 'src/Dropdown/index.ts',
    'MultiSelect/index': 'src/MultiSelect/index.ts',
    'DatePicker/index': 'src/DatePicker/index.ts',
    'FileUpload/index': 'src/FileUpload/index.ts',
    'CommandPalette/index': 'src/CommandPalette/index.ts',
    'Sidebar/index': 'src/Sidebar/index.ts',
    'NotificationCenter/index': 'src/NotificationCenter/index.ts',
    'Badge/index': 'src/Badge/index.ts',
    'Alert/index': 'src/Alert/index.ts',
    'Avatar/index': 'src/Avatar/index.ts',
    'Input/index': 'src/Input/index.ts',
    'Textarea/index': 'src/Textarea/index.ts',
    'Checkbox/index': 'src/Checkbox/index.ts',
    'Switch/index': 'src/Switch/index.ts',
    'RadioGroup/index': 'src/RadioGroup/index.ts',
    'Select/index': 'src/Select/index.ts',
    'Slider/index': 'src/Slider/index.ts',
  },
  format: ['cjs', 'esm'],
  dts: true,
  clean: true,
  sourcemap: true,
  external: ['react', 'react-dom'],
});
